### ISSUE TITLE
some inconsistency in flags: --max-step vs --max-steps

### ISSUE THREAD

**Issue by gfursin** [LPD-EPFL/AggregaThor#2]
I just noticed a small inconsistency: in some places you use flag --max-step and in other places --max-steps . It may be useful to make it consistent ...
Thanks a lot!

**Comment by srlt** [comment]
Thanks!
To follow the usage examples, `--max-step` has been chosen over `--max-steps`.

Should be corrected in commit 6e39268d653f887377d05ce8d2fc3106a0e782f4.
